Implemented AppendCampaign Model
srs-adamr/LiveVox.NET pull request #1
Opened 2023-11-03 15:04 UTC by srs-vimalk

Implemented AppendCampaign Model

2023-11-03 16:21 UTC, srs-adamr requested changes
Please correct the folder structure and placement of files.

2023-11-03 16:22 UTC, srs-adamr requested changes

2023-11-03 16:22 UTC, srs-adamr commented on LiveVox.NET/Models/Campaign/AppendCampaign/AppendCampaignResponse.cs
There is no response object, so please remove this.

2023-11-03 16:35 UTC, srs-vimalk commented on LiveVox.NET/Models/Campaign/AppendCampaign/AppendCampaignResponse.cs
I have removed this

2023-11-03 16:36 UTC, srs-vimalk commented on LiveVox.NET/Models/Campaign/AppendCampaign/AppendCampaignResponse.cs
also change the folder structure let me know if we need any changes

2023-11-03 17:44 UTC, srs-adamr commented on LiveVox.NET/Models/Campaign/Requests/AppendCampaignRequest.cs
> +namespace LiveVox.NET.Models.Campaign.AppendCampaign
Correct namespace

2023-11-03 17:44 UTC, srs-adamr commented on LiveVox.NET/Models/Campaign/Requests/CreateCampaignRequest.cs
> +namespace LiveVox.NET.Models.Campaign.CreateCampaign
Correct namespace

2023-11-03 17:44 UTC, srs-adamr commented on LiveVox.NET/Models/Campaign/Responses/CreateCampaignResponse.cs
> +namespace LiveVox.NET.Models.Campaign.CreateCampaign
Correct namespace

2023-11-06 17:59 UTC, srs-vimalk commented
Implemented Response and Request model

1. AppendCampaignRecord
2. CreateCampaign
3. DeactivateCampaign
4. FindMatchingCampaigns
5. FindMatchingFinishedCalls
6. GetCampaignListInfo
7. ListCampaigns
8. ListCampaignTransactions
9. ReadCampaign
10. UpdateCampaign
11. UpdateCampaignState
﻿committed changes

2023-11-06 18:23 UTC, srs-adamr requested changes
Please review changes, ensure all requests/responses properties that are being used in a body have their json attributes.

2023-11-06 18:23 UTC, srs-adamr commented on LiveVox.NET/Models/Campaign/Common/AccountTransactionEntry.cs
This file is missing it's Json attributes.

2023-11-06 18:23 UTC, srs-adamr commented on LiveVox.NET/Models/Campaign/Common/CampaignFIle.cs
This file is missing it's json attributes

2023-11-06 18:23 UTC, srs-adamr commented on LiveVox.NET/Models/Campaign/Common/Consumer.cs
This file is missing it's json attributes

2023-11-06 18:23 UTC, srs-adamr commented on LiveVox.NET/Models/Campaign/Common/Consumer.cs
> +        public DateTime? DateOfBirth { get; set; }
Double check this format, most likely it is also a Unix MS timestamp

2023-11-06 18:23 UTC, srs-adamr commented on LiveVox.NET/Models/Campaign/Requests/ListCampaignTransactionsRequest.cs
> +        public string? TransactionList { get; set; } = "transactionList";
What is this for?

2023-11-06 18:23 UTC, srs-adamr commented on LiveVox.NET/Models/Campaign/Responses/CreateCampaignResponse.cs
Json attributes missing

2023-11-06 18:23 UTC, srs-adamr commented on LiveVox.NET/Models/Campaign/Responses/ReadCampaignResponse.cs
Json Attrbutes missing

2023-11-06 19:53 UTC, srs-vimalk commented on LiveVox.NET/Models/Campaign/Responses/ReadCampaignResponse.cs
I had made the changes, can you please review it

2023-11-06 20:09 UTC, srs-adamr commented on LiveVox.NET/Models/Campaign/Requests/AppendCampaignRequest.cs
>          public Method RequestType { get; set; } = Method.Put;
RequestType also needs ignored.

2023-11-06 20:11 UTC, srs-adamr requested changes
Still need some namespace corrections, and JsonIgnore for RequestTypes

2023-11-06 20:17 UTC, srs-adamr approved these changes
Looks good.

2023-11-06 20:29 UTC, srs-binnys approved these changes

2023-11-06 20:39 UTC, merged