Implemented Account API
srs-adamr/LiveVox.NET pull request #4
Opened 2023-11-08 16:30 UTC by srs-vimalk

Account
Create Account
Create Multiple Accounts
Read Account
List Accounts
Find Matching Accounts
Update Account
Add Note to Account
Delete Account

Link / Unlink Account to Contacts
Link Account to Contact
Link Account to Multiple Contacts
Unlink an Account With a Contact
Account Classifications

Create Classification
Read Classification
List All Classifications
Update Classification
Delete Classification

Account Types
Create Type
Read Type
List All Types
Update Type
Delete Type

2023-11-08 17:56 UTC, srs-adamr requested changes
Please review comments

2023-11-08 17:56 UTC, srs-adamr commented on LiveVox.NET/LiveVox.NET.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
Remove this, we are using system.Text.Json

2023-11-08 17:56 UTC, srs-adamr commented on LiveVox.NET/Models/Account/Requests/LinkAccountToContactRequest.cs
Missing Url Segment

2023-11-08 17:56 UTC, srs-adamr commented on LiveVox.NET/Models/Account/Requests/ListAllAccountTypeRequest.cs
This looks incomplete.

2023-11-08 17:56 UTC, srs-adamr commented on LiveVox.NET/Models/Account/Requests/ListAllClassificationRequest.cs
This looks incomplete

2023-11-08 17:56 UTC, srs-adamr commented on LiveVox.NET/Models/Account/Requests/ReadAccountRequest.cs
This looks incomplete.

2023-11-08 17:56 UTC, srs-adamr commented on LiveVox.NET/Models/Account/Requests/ReadAccountTypeRequest.cs
This looks incomplete.

2023-11-08 17:56 UTC, srs-adamr commented on LiveVox.NET/Models/Account/Requests/ReadClassificationRequest.cs
This looks incomplete.

2023-11-08 17:56 UTC, srs-adamr commented on LiveVox.NET/Models/Account/Responses/ListAllClassificationResponse.cs
This is missing Json attributes

2023-11-13 13:30 UTC, srs-adamr approved these changes

2023-11-13 15:11 UTC, srs-binnys approved these changes

2023-11-13 15:11 UTC, srs-binnys commented on LiveVox.NET/Models/Account/Common/Account.cs
> +        public Guid LogId { get; set; }
@srs-vimalk pls check if we need Guid's or if we can have string instead.

2023-11-13 16:02 UTC, merged