Call control api
srs-adamr/LiveVox.NET pull request #5
Opened 2023-11-13 18:40 UTC by srs-binnys

2023-11-13 20:03 UTC, srs-adamr requested changes
Few things, looks good otherwise!

2023-11-13 20:03 UTC, srs-adamr commented on LiveVox.NET/LiveVox.NET.csproj
> +    <EmbeddedResource Remove="Models\CallControl\**" />
Check on this

2023-11-13 20:03 UTC, srs-adamr commented on LiveVox.NET/Models/Call/Enumerations/ErrorCode.cs
This is commented

2023-11-13 20:03 UTC, srs-adamr commented on LiveVox.NET/Models/Call/Requests/Agent/PreviewDial/PlayMessageRequest.cs
This is in the wrong namespace. Should be in the Message namespace.

2023-11-13 21:27 UTC, srs-binnys commented on LiveVox.NET/LiveVox.NET.csproj
> +    <EmbeddedResource Remove="Models\CallControl\**" />
Have removed these lines Adam, they were not required.

2023-11-13 21:29 UTC, srs-binnys commented on LiveVox.NET/Models/Call/Enumerations/ErrorCode.cs
Uncommented the error codes.

2023-11-13 21:29 UTC, srs-binnys commented on LiveVox.NET/Models/Call/Requests/Agent/PreviewDial/PlayMessageRequest.cs
Moved the files to Message Namespace.

2023-11-13 21:42 UTC, srs-binnys commented on LiveVox.NET/Models/Call/Enumerations/ErrorCode.cs
> +        [JsonPropertyName("440")]
@srs-adamr here we have two properties with the same value Busy, 
the same for OutsideOfAllowableDialingWindow too.

2023-11-14 14:55 UTC, srs-adamr approved these changes

2023-11-14 15:00 UTC, srs-vimalk approved these changes

2023-11-14 15:06 UTC, merged